test_infra_ref: &test_infra_ref
  org: kyma-project
  repo: test-infra
  path_alias: github.com/kyma-project/test-infra

job_template: &job_template
  skip_report: false
  decorate: true
  path_alias: github.com/kyma-project/kyma
  max_concurrency: 10
  spec:
    containers:
    - image: eu.gcr.io/kyma-project/test-infra/buildpack-golang:go1.12
      securityContext:
        privileged: true
      command:
      - "/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/build.sh"
      args:
      - "/home/prow/go/src/github.com/kyma-project/kyma/components/iam-kubeconfig-service"
      resources:
        requests:
          memory: 1.5Gi
          cpu: 0.8

job_labels_template: &job_labels_template
  preset-dind-enabled: "true"
  preset-sa-gcr-push: "true"
  preset-docker-push-repository: "true"

presubmits: # runs on PRs
  kyma-project/kyma:
  - name: pre-master-kyma-components-iam-kubeconfig-service
    branches:
    - ^master$
    <<: *job_template
    run_if_changed: "^components/iam-kubeconfig-service/"
    extra_refs:
    - <<: *test_infra_ref
      base_ref: master
    labels:
      <<: *job_labels_template
      preset-build-pr: "true"
  - name: pre-rel14-kyma-components-iam-kubeconfig-service
    branches:
    - release-1.4
    <<: *job_template
    always_run: true
    extra_refs:
    - <<: *test_infra_ref
      base_ref: release-1.4
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
  - name: pre-rel13-kyma-components-iam-kubeconfig-service
    branches:
    - release-1.3
    <<: *job_template
    always_run: true
    extra_refs:
    - <<: *test_infra_ref
      base_ref: release-1.3
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
  - name: pre-rel12-kyma-components-iam-kubeconfig-service
    branches:
      - release-1.2
    <<: *job_template
    always_run: true
    extra_refs:
      - <<: *test_infra_ref
        base_ref: release-1.2
    labels:
      <<: *job_labels_template
      preset-build-release: "true"

postsubmits:
  kyma-project/kyma:
  - name: post-master-kyma-components-iam-kubeconfig-service
    branches:
    - ^master$
    <<: *job_template
    run_if_changed: "^components/iam-kubeconfig-service/"
    extra_refs:
    - <<: *test_infra_ref
      base_ref: master
    labels:
      <<: *job_labels_template
      preset-build-master: "true"
