# Github connector application name. Must match name from Application resource.
appName: "github-connector"
webhookGateway:
  # Github webhook gateway container listening port for incoming webhooks.
  containerPort: 8080
  # Github webhook gateway image.
  image: "eu.gcr.io/kyma-project/test-infra/github-webhook-gateway:PR-3267"
  # Secret set for Github webhooks.
  webhookSecretValue: "dummy-secret"
  # Slack channel name to send messages.
  notificationSlackChannel: "kyma-team"
  # Kyma cluster FQDN.
  eventPublisherProxyURL: "http://eventing-event-publisher-proxy.kyma-system/publish"
# Slack connector application name. Must match name from Application resource.
#slackAppName: "slack-connector"
# Slack application plan suffix. Must match suffix from CMP.
#cmpSlackAppPlanSuffix: "36130"
# Github application plan suffix. Must match suffix from CMP.
cmpAppPlanSuffix: "a249d"
# Kyma cluster FQDN.
kymaClusterHostname: "c-6751197.kyma.shoot.live.k8s-hana.ondemand.com"

slackConnector:
  # Slack connector application name. Must match name from Application resource.
  slackAppName: "slack-connector"
  # Slack connector API ID
  apiId: "85ded56e-303b-43b3-a950-8b1c3d519561"
  # Slack application plan base name
  cmpSlackAppPlan: "slack-connector"
  # Slack application plan suffix. Must match suffix from CMP.
  cmpSlackAppPlanSuffix: "36130"
  # Secret name with slack bot token.
  botTokenSecret: "slack-bot-token"
  # Secret key name with slack bot token.
  botTokenSecretKey: "token"
  # Token fake value.
  botToken: "fake_token"

function:
  issues:
    labeled:
      # Repository URL with function code.
      repositoryUrl: "https://github.com/kyma-project/test-infra.git"
      # Path to directory with function code. Relative to repository root.
      functionBaseDir: "/development/kyma-github-connector/issueLabeledFunction"
      # Branch name with function code.
      branch: "main"
