# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "go"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
    ignore:
      - dependency-name: "github.com/go-logr/logr"
        versions:
          - "1.2.2"
          - "1.2.1"
          - "1.2.0"
          - "1.2.0-rc1"
          - "1.1.0"
          - "1.1.0-rc1"
          - "1.0.0"
          - "1.0.0-rc1"
      - dependency-name: "k8s.io/apimachinery"
        versions:
          - "0.2x"
      - dependency-name: "k8s.io/api"
        versions:
          - "0.2x"
      - dependency-name: "k8s.io/client-go"
        versions:
          - "0.2x"
  - package-ecosystem: "terraform"
    directory: "configs/terraform/secrets-leaks-log-scanner"
    labels:
      - "terraform"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "tf"
      include: "scope"
  - package-ecosystem: "terraform"
    directory: "configs/terraform/core"
    labels:
      - "terraform"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "tf"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/ginkgo"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ginkgo"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/tools/githubrelease"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "githubrelease"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/clonerefs"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "clonerefs"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/kyma-integration"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "kyma-integrate"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/whitesource-scanner"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "whitesource"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/golangci-lint"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "golangci-lint"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/needs-tws-external-plugin"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "tws-plugin"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/prow/images/cla-assistant-external-plugin"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "cla-plugin"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/cloud-run/move-gcs-bucket"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "move-gcs-bucket"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/cloud-run/slack-message-sender"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "slack-msg-sender"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/cloud-run/rotate-service-account"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker-rotate-sa"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/cloud-run/service-account-keys-cleaner"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker-glean-sa"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/image-detector"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "image-detector"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/image-builder/images/kaniko"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "image-builder"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/cmd/image-builder/images/buildkit"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "buildkit-image-builder"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/unified-agent/nodejs"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "unified-agent-nodejs"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/unified-agent/go"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "unified-agent-go"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/unified-agent"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "unified-agent"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/e2e-dind-gcloud"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "e2e-dind-gcloud"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/e2e-dind-garden"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "e2e-dind-garden"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/e2e-dind-nodejs"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "e2e-dind-nodejs"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/e2e-dind-k3d"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "e2e-dind-k3d"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/alpine/shellcheck"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "alpine-shellcheck"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/alpine/hadolint"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "alpine-hadolint"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/alpine/git/gke-aws-auth"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "alpine-git-gke-aws-auth"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/alpine/git"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "alpine-git"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/alpine"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "alpine"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/buildpack/go"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "buildpack-go"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/images/buildpack"
    labels:
      - "docker"
      - "skip-review"
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "buildpack"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions"
      include: "scope"
    ignore:
      - dependency-name: "ahmadnassri/action-workflow-queue"
      - dependency-name: "gaurav-nelson/github-action-markdown-link-check"
      - dependency-name: "slackapi/slack-github-action"
      - dependency-name: "shmokmt/actions-setup-tfcmt"
      - dependency-name: "gitleaks/gitleaks-action"
