webhookGateway:
  containerPort: 8080
  image: "eu.gcr.io/kyma-project/test-infra/github-webhook-gateway:1.1.0"
  webhookSecretValue: "dummy-secret"
appName: "github-connector"
slackAppName: "slack-connector"
cmpSlackAppPlanSuffix: "36130"
cmpAppPlanSuffix: "a249d"
kymaClusterHostname: "c-6751197.kyma.shoot.live.k8s-hana.ondemand.com"

function:
  issues:
    labeled:
      repositoryUrl: "https://github.com/kyma-project/test-infra.git"
      functionBaseDir: "/development/github-slack-connector/issueLabeledFunction"
      branch: "master"
