functionEnabled: true
# Forwarded event type
eventType: "oomevent.found.v1"
# Slack channel name to send messages.
notificationSlackChannel: "neighbors-dev-test"
# Path to directory with function code. Relative to repository root.
functionBaseDir: "/development/kyma-slack-connector/oomFoundFunction"
# Branch name with function code.
branch: "slack_tooling_rc"
