job_template: &job_template
  skip_report: true
  run_if_changed: "^components/application-operator/"
  decorate: true
  path_alias: github.com/kyma-project/kyma
  max_concurrency: 10
  extra_refs:
    - org: kyma-project
      repo: test-infra
      base_ref: master
      path_alias: github.com/kyma-project/test-infra
  spec:
    containers:
      - image: eu.gcr.io/kyma-project/prow/test-infra/buildpack-golang:v20181119-afd3fbd
        securityContext:
          privileged: true
        command:
          - "/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/build.sh"
        args:
          - "/home/prow/go/src/github.com/kyma-project/kyma/components/application-operator"
    resources:
      requests:
        memory: 1.5Gi
        cpu: 0.8
      limits:
        memory: 2Gi
        cpu: 1.4

job_labels_template: &job_labels_template
  preset-dind-enabled: "true"
  preset-sa-gcr-push: "true"
  preset-docker-push-repository: "true"

presubmits: # runs on PRs
  kyma-project/kyma:
    - name: kyma-components-application-operator
      branches:
        - master
      <<: *job_template
      labels:
        <<: *job_labels_template
        preset-build-pr: "true"

postsubmits:
  kyma-project/kyma:
    - name: kyma-components-application-operator
      branches:
        - master
      <<: *job_template
      labels:
        <<: *job_labels_template
        preset-build-master: "true"
