job_template: &job_template
  skip_report: false
  decorate: true
  path_alias: github.com/kyma-incubator/varkes
  max_concurrency: 10
  extra_refs:
    - org: kyma-project
      repo: test-infra
      base_ref: master
      path_alias: github.com/kyma-project/test-infra
  spec:
    containers:
      - image: eu.gcr.io/kyma-project/prow/test-infra/buildpack-node:v20181130-b28250b
        securityContext:
          privileged: true
        command:
          - "/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/build.sh"
        args:
          - "/home/prow/go/src/github.com/kyma-incubator/varkes/openapi-mock"

job_labels_template: &job_labels_template
  preset-dind-enabled: "true"
  preset-sa-gcr-push: "true"
  preset-docker-push-repository-incubator: "true"

presubmits: # runs on PRs
  kyma-incubator/varkes:
    - name: varkes-openapi-mock
      always_run: true
      branches:
        - master
      run_if_changed: "^openapi-mock/"
      <<: *job_template
      labels:
        <<: *job_labels_template
        preset-build-pr: "true"

postsubmits:
  kyma-incubator/varkes:
    - name: varkes-openapi-mock
      branches:
        - master
      <<: *job_template
      labels:
        <<: *job_labels_template
        preset-build-master: "true"