# slackBotToken must be provided using --set argument to helm command.
# It provides token value used to communicate with slack.
slackApplicationEnabled: false
slackBotTokenSecretEnabled: false
#gitRepositoryEnabled: false
global:
  # Slack connector application name.
  appName: "mp-sap-slack-connector"
  # Slack connector API ID
  apiId: "2906b647-0dfe-4bf0-98e8-1c50d0348550"
  # Slack application plan base name
  cmpSlackAppPlan: "slack-connector"
  # Slack application plan suffix. Must match suffix from CMP.
  cmpSlackAppPlanSuffix: "4af0a"
  # Repository name with functions code.
  repositoryName: "tooling-serverless-functions"
  # Repository URL with function code.
  repositoryUrl: "https://github.com/kyma-test-infra-dev/tooling-serverless-functions.git"
  # Slack application helm release name.
  #slackAppHelmReleaseName: "slack-application"
  slackAppHelmReleaseName: "common"
