kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "stability-checker.name" . }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
  resourceNames:
    - "{{ .Chart.Name }}-test-results"

- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list"]

- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","get","delete"]

- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

- apiGroups: ["addons.kyma-project.io"]
  resources: ["clusteraddonsconfigurations"]
  verbs: ["create", "delete", "get", "patch"]
  resourceNames:
    - "testing-addons"
