apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.ciForceBot.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName | quote }}
    release: {{ .Release.Name | quote }}
    service: {{ .Values.ciForceBot.name | quote }}
data:
  kymaEventingProxy: {{ .Values.kymaEventingProxy | quote }}
  appName: {{ .Values.appName | quote }}
  listenPort: {{ .Values.ciForceBot.ciForceBotContainer.containerPort | quote }}
  firebaseProjectID: {{ .Values.ciForceBot.firebaseProjectID | quote }}
