apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-gh-webhook-gateway-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: "mp-{{ .Values.appName }}"
    release: {{ .Release.Name | quote }}
data:
  #kymaEventsService: "http://mp-{{ .Values.appName }}-event-service.kyma-integration:8081/mp-{{ .Values.appName }}/v1/events"
  kymaEventingProxy: {{ .Values.webhookGateway.eventPublisherProxyURL | quote }}
  #kymaEventsPort: "8081"
  ghWebhookGatewayPodPort: {{ .Values.webhookGateway.containerPort | quote }}
  slackChannel: {{ default "kyma-prow-dev-null" .Values.webhookGateway.notificationSlackChannel | quote}}
