apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.appName }}"
    release: {{ .Release.Name | quote }}
data:
  kymaEventingProxy: {{ .Values.webhookGateway.eventPublisherProxyURL | quote }}
  destinationEventingAppName: {{ .Values.slackConnectorAppName | quote }}
  sapToolsGithubWebhookGatewayContainerPort: {{ .Values.webhookGateway.sapToolsRepo.containerPort | quote }}
  kymaGithubWebhookGatewayContainerPort: {{ .Values.webhookGateway.kymaRepo.containerPort | quote }}
  sapToolsGithubWebhookUrlPath: {{ .Values.webhookGateway.sapToolsRepo.githubWebhookUrlPath }}
  kymaGithubWebhookUrlPath: {{ .Values.webhookGateway.kymaRepo.githubWebhookUrlPath }}
