apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: saptoolsghwebhookgateway
        imagePullPolicy: Always
        image: {{ .Values.webhookGateway.image }}
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
        - containerPort: {{ .Values.webhookGateway.sapToolsRepo.containerPort }}
        env:
        - name: GITHUB_WEBHOOK_GATEWAY_NAME
          value: {{ .Release.Name }}-{{ .Values.webhookGateway.name }}-{{ .Values.webhookGateway.sapToolsRepo.repo }}
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.webhookGateway.name }}
              key: sapToolsGithubWebhookSecret
        - name: EVENTING_SERVICE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
              key: kymaEventingProxy
        - name: LISTEN_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
              key: sapToolsGithubWebhookGatewayContainerPort
        - name: DESTINATION_EVENTING_APP_NAME
          valueFrom:
            configMapKeyRef:
              key: destinationEventingAppName
              name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
        - name: GITHUB_WEBHOOK_URL_PATH
          valueFrom:
            configMapKeyRef:
              key: sapToolsGithubWebhookUrlPath
              name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
      - name: kymaghwebhookgateway
        imagePullPolicy: Always
        image: {{ .Values.webhookGateway.image }}
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
          - containerPort: {{ .Values.webhookGateway.kymaRepo.containerPort }}
        env:
          - name: GITHUB_WEBHOOK_GATEWAY_NAME
            value: {{ .Release.Name }}-{{ .Values.webhookGateway.name }}-{{ .Values.webhookGateway.kymaRepo.repo }}
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.webhookGateway.name }}
                key: kymaGithubWebhookSecret
          - name: EVENTING_SERVICE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
                key: kymaEventingProxy
          - name: LISTEN_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
                key: kymaGithubWebhookGatewayContainerPort
          - name: DESTINATION_EVENTING_APP_NAME
            valueFrom:
              configMapKeyRef:
                key: destinationEventingAppName
                name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
          - name: GITHUB_WEBHOOK_URL_PATH
            valueFrom:
              configMapKeyRef:
                key: kymaGithubWebhookUrlPath
                name: {{ .Release.Name}}-{{ .Values.webhookGateway.name }}
