required = [
  "github.com/golang/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  version = "v8.0.0"
  name = "k8s.io/client-go"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "k8s.io/test-infra"

# Need override because release-1.11 and kubernetes-1.11.0 are not semver compliant
[[override]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"
