required = [
  "golang.org/x/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  version = "kubernetes-1.11.2"
  name = "k8s.io/client-go"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  revision = "b9a576b397892c55487e495721d23b3a52ac9472"
  name = "k8s.io/test-infra"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v21.0.0"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

# github.com/Huang-Wei/shared-loadbalancer/vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure
# Fix vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:246:4: cannot use expiresIn (type string) as type json.Number in field value
# Fix vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:247:4: cannot use expiresOn (type string) as type json.Number in field value
# Fix vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:248:4: cannot use expiresOn (type string) as type json.Number in field value
# Fix vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:265:23: cannot use token.token.ExpiresIn (type json.Number) as type string in assignment
# Fix vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:266:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment
[[override]]
name = "github.com/Azure/go-autorest"
revision = "bca49d5b51a50dc5bb17bbf6204c711c6dbded06"

# Need override because release-1.11 and kubernetes-1.11.0 are not semver compliant
[[override]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.52.0"
