presubmits: # runs on PRs
  kyma-project/kyma-environment-broker:
    - name: pre-kyma-environment-broker
      annotations:
        owner: "gopher"
        description: "Main KEB unit testing pipeline"
      labels:
        prow.k8s.io/pubsub.project: "sap-kyma-prow"
        prow.k8s.io/pubsub.runID: "pre-kyma-environment-broker"
        prow.k8s.io/pubsub.topic: "prowjobs"
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      run_if_changed: ".+|^scripts/"
      skip_report: false
      decorate: true
      cluster: untrusted-workload
      max_concurrency: 10
      branches:
        - ^master$
        - ^main$
      spec:
        containers:
          - image: "europe-docker.pkg.dev/kyma-project/prod/testimages/e2e-dind-k3d:v20231121-05130964"
            securityContext:
              privileged: true
              seccompProfile:
                type: Unconfined
              allowPrivilegeEscalation: true
            command:
              - /init.sh
              - bash
              - -c
            args:
              - |-
                make release
            resources:
              requests:
                memory: 3Gi
                cpu: 2
