gitHubLogin: "kyma-bot"
gitHubToken: "/etc/github/token"
gitName: "Kyma Bot"
gitEmail: "kyma.bot@sap.com"
skipPullRequest: false
gitHubOrg: "kyma-project"
gitHubRepo: "test-infra"
remoteName: "test-infra-1"
upstreamURLBase: "https://raw.githubusercontent.com/kyma-project/test-infra/main"
headBranchName: "test-infra-autobump"
includedConfigPaths:
  - "." # test-infra root directory
excludedConfigPaths:
  - "prow/staging"
  - "sec-scanners-config.yaml"
targetVersion: "latest"
prefixes:
  - name: "kyma-project/prod"
    prefix: "europe-docker.pkg.dev/kyma-project/prod/"
    refConfigFile: "templates/config.yaml"
    stagingRefConfigFile: "templates/config.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: false
