gitHubLogin: "kyma-bot"
gitHubToken: "/etc/github/token"
gitName: "Kyma Bot"
gitEmail: "kyma.bot@sap.com"
skipPullRequest: false
gitHubOrg: "kyma-project"
gitHubRepo: "test-infra"
remoteName: "test-infra-1"
upstreamURLBase: "https://raw.githubusercontent.com/kyma-project/test-infra/main"
headBranchName: "test-infra-autobump"
includedConfigPaths:
  - "." # test-infra root directory
excludedConfigPaths:
  - "prow/staging"
  - "sec-scanners-config.yaml"
extraFiles:
  - "configs/terraform/core/apis.tf"
  - "configs/terraform/environments/dev/artifact-registry/main.tf"
  - "configs/terraform/environments/dev/artifact-registry/output.tf"
  - "configs/terraform/environments/dev/artifact-registry/provider.tf"
  - "configs/terraform/environments/dev/artifact-registry/terraform.tfvars"
  - "configs/terraform/environments/dev/artifact-registry/variables.tf"
  - "configs/terraform/environments/dev/opa-gatekeeper/backend.tf"
  - "configs/terraform/environments/dev/opa-gatekeeper/main.tf"
  - "configs/terraform/environments/dev/opa-gatekeeper/output.tf"
  - "configs/terraform/environments/dev/opa-gatekeeper/provider.tf"
  - "configs/terraform/environments/dev/opa-gatekeeper/terraform.tfvars"
  - "configs/terraform/environments/dev/opa-gatekeeper/variables.tf"
  - "configs/terraform/environments/dev/secrets-rotator/backend.tf"
  - "configs/terraform/environments/dev/secrets-rotator/main.tf"
  - "configs/terraform/environments/dev/secrets-rotator/provider.tf"
  - "configs/terraform/environments/dev/secrets-rotator/terraform.tfvars"
  - "configs/terraform/environments/dev/secrets-rotator/variables.tf"
  - "configs/terraform/environments/prod/artifact-registry-variables.tf"
  - "configs/terraform/environments/prod/artifact-registry.tf"
  - "configs/terraform/environments/prod/backend.tf"
  - "configs/terraform/environments/prod/cors-proxy.tf"
  - "configs/terraform/environments/prod/dns-collector.tf"
  - "configs/terraform/environments/prod/dns.tf"
  - "configs/terraform/environments/prod/gcp-workfload-identity-federation-variables.tf"
  - "configs/terraform/environments/prod/gcp-workfload-identity-federation.tf"
  - "configs/terraform/environments/prod/github-com.tf"
  - "configs/terraform/environments/prod/github-webhook-gateway.tf"
  - "configs/terraform/environments/prod/image-builder-variables.tf"
  - "configs/terraform/environments/prod/image-builder.tf"
  - "configs/terraform/environments/prod/kyma-bots-secrets-variables.tf"
  - "configs/terraform/environments/prod/kyma-bots-secrets.tf"
  - "configs/terraform/environments/prod/network-policy.tf"
  - "configs/terraform/environments/prod/opa-gatekeeper-variables.tf"
  - "configs/terraform/environments/prod/opa-gatekeeper.tf"
  - "configs/terraform/environments/prod/output.tf"
  - "configs/terraform/environments/prod/pjtester-variables.tf"
  - "configs/terraform/environments/prod/pjtester.tf"
  - "configs/terraform/environments/prod/provider.tf"
  - "configs/terraform/environments/prod/prow-external-plugins.tf"
  - "configs/terraform/environments/prod/prow.tf"
  - "configs/terraform/environments/prod/secrets-leaks-log-scanner.tf"
  - "configs/terraform/environments/prod/secrets-rotator.tf"
  - "configs/terraform/environments/prod/security-dashboard-token.tf"
  - "configs/terraform/environments/prod/slack-message-sender.tf"
  - "configs/terraform/environments/prod/terraform-service-accounts-variables.tf"
  - "configs/terraform/environments/prod/terraform-service-accounts.tf"
  - "configs/terraform/environments/prod/terraform.tfvars"
  - "configs/terraform/environments/prod/variables.tf"
  - "configs/terraform/modules/artifact-registry/main.tf"
  - "configs/terraform/modules/artifact-registry/output.tf"
  - "configs/terraform/modules/artifact-registry/provider.tf"
  - "configs/terraform/modules/artifact-registry/variables.tf"
  - "configs/terraform/modules/cors-proxy/cors-proxy.tf"
  - "configs/terraform/modules/cors-proxy/main.tf"
  - "configs/terraform/modules/gcp-workload-identity-federation/main.tf"
  - "configs/terraform/modules/gcp-workload-identity-federation/outputs.tf"
  - "configs/terraform/modules/gcp-workload-identity-federation/provider.tf"
  - "configs/terraform/modules/gcp-workload-identity-federation/variables.tf"
  - "configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf"
  - "configs/terraform/modules/github-webhook-gateway/main.tf"
  - "configs/terraform/modules/opa-gatekeeper/main.tf"
  - "configs/terraform/modules/opa-gatekeeper/output.tf"
  - "configs/terraform/modules/opa-gatekeeper/provider.tf"
  - "configs/terraform/modules/opa-gatekeeper/variables.tf"
  - "configs/terraform/modules/rotate-service-account/main.tf"
  - "configs/terraform/modules/rotate-service-account/output.tf"
  - "configs/terraform/modules/rotate-service-account/provider.tf"
  - "configs/terraform/modules/rotate-service-account/variables.tf"
  - "configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf"
  - "configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf"
  - "configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf"
  - "configs/terraform/modules/secrets-leaks-log-scanner/main.tf"
  - "configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-detector.tf"
  - "configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf"
  - "configs/terraform/modules/security-dashboard-token/main.tf"
  - "configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf"
  - "configs/terraform/modules/service-account-keys-cleaner/main.tf"
  - "configs/terraform/modules/service-account-keys-cleaner/output.tf"
  - "configs/terraform/modules/service-account-keys-cleaner/provider.tf"
  - "configs/terraform/modules/service-account-keys-cleaner/variables.tf"
  - "configs/terraform/modules/slack-message-sender/issue-labeled.tf"
  - "configs/terraform/modules/slack-message-sender/main.tf"
  - "configs/terraform/modules/slack-message-sender/release-cluster-created.tf"
  - "configs/terraform/modules/slack-message-sender/slack-message-sender.tf"
targetVersion: "latest"
prefixes:
  - name: "test-infra"
    prefix: "eu.gcr.io/kyma-project/test-infra/"
    refConfigFile: "templates/config.yaml"
    stagingRefConfigFile: "templates/config.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: false
  - name: "testimages"
    prefix: "europe-docker.pkg.dev/kyma-project/prod/testimages/"
    refConfigFile: "templates/config.yaml"
    stagingRefConfigFile: "templates/config.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: true
  - name: "test-infra-prod"
    prefix: "europe-docker.pkg.dev/kyma-project/prod/test-infra/"
    refConfigFile: "templates/config.yaml"
    stagingRefConfigFile: "templates/config.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: false
  - name: "image-builder"
    prefix: "europe-docker.pkg.dev/kyma-project/prod/image-builder"
    refConfigFile: "templates/config.yaml"
    stagingRefConfigFile: "templates/config.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: false
  - name: "buildkit-image-builder"
    prefix: "europe-docker.pkg.dev/kyma-project/prod/buildkit-image-builder"
    refConfigFile: "templates/config.yaml"
    stagingRefConfigFile: "templates/config.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: false
