nameOverride: ""
fullnameOverride: ""

deployment:
  image: eu.gcr.io/kyma-project/test-infra/probot-stale:v20211223-7d9f748d
  imagePullPolicy: IfNotPresent
  config:
    # https://probot.github.io/docs/configuration/
    port: 8080
    logLevel: info
    webhookPath: /webhook
    disableStats: true
    githubHost: github.tools.sap
    githubProtocol: https
    appIDSecretName: probot-stale
    privateKeySecretName: probot-stale
    webhookSecretsSecretName: probot-stale
  resources: {}

ingress:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stalebot-ip
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: probot-stale
    networking.gke.io/v1beta1.FrontendConfig: "probot-stale-frontend-config"
  path: /*
  host: stale.build.kyma-project.io
  frontendConfig:
    name: probot-stale-frontend-config
    sslPolicy: custom-ssl-policy

service:
  type: NodePort
  port: 80
