# base64GcpServiceAccountKey must be provided using --set argument to helm command.
# base64GcpServiceAccountKey provides base64 encoded google service account json key file.
# Github connector application name. Must match name from Application resource.
appName: "ci-force-bot"
# Kyma cluster FQDN.
kymaClusterHostname: "c-6751197.kyma.shoot.live.k8s-hana.ondemand.com"
kymaEventingProxy: "http://eventing-event-publisher-proxy.kyma-system/publish"
firebaseProjectID: "sap-kyma-prow"
firestoreCollectionName: "failed-prowjobs"
gcpServiceAccount: "ci-force-bot-tooling-kyma"
component: "ci-force-bot.tooling.kyma"
replicas: 1
# TODO: Change this property name in all charts to match this one.
# Kyma eventing application name to subscribe events for.
kymaEventingSubscriptionAppName: "github-connector"
# Event type published to Kyma
eventType: "issuesevent.closed.v1"
container:
  name: "ciforcebot"
  # change to match value from makefile
  image: eu.gcr.io/kyma-project/test-infra/ci-force-bot:PR-4558
  containerPort: 8080
  resources:
    limits:
      mem: 256Mi
      cpu: 500m
    containerPort: 8080
