# Github connector application name. Must match name from Application resource.
appName: "ci-force-bot"
# Kyma cluster FQDN.
kymaClusterHostname: "ddf1313.kyma-stage.shoot.live.k8s-hana.ondemand.com"
kymaEventingProxy: "http://eventing-event-publisher-proxy.kyma-system/publish"
ciForceBot:
  name: ci-force-bot
  firebaseProjectID: "sap-kyma-neighbors-dev"
  serviceAccount: "dev-kyma-tooling-ci-force-bot"
  base64SerivceAccountKey: "dummy"
  subscriptionAppName: "github-connector"
  replicas: 1
  # Event type published to Kyma
  eventType: "issuesevent"
  # Event type published to Kyma
  eventAction: "closed"
  # Event type published to Kyma
  eventVersion: "v1"
  ciForceBotContainer:
    name: ciforcebot
    # change to match value from makefile
    image: eu.gcr.io/kyma-project/test-infra/pr/ci-force-bot:PR-3961
    limitsMem: 256Mi
    limitsCpu: 500m
    containerPort: 8080
