cluster_name: test-prow
oauth: testoauth999
project: sap-kyma-neighbors-dev
zone: europe-west3-c
location: europe-west3
buckets:
  - test-prow-bucket
  - test-prow-bucket-2
keyring_name: test-prow-keyring
encryption_key_name: test-prow-key
kubeconfig: ""
prefix: ""
labels:
  created-by: user-name # TODO can we somehow dynamically label this based on credentials file we give to a script?

clusters:
  - name: test-prow
    location: europe-west3-c
    description: "Test prow cluster"
    #    labels:
    #      cluster-specific: label
    kubernetesVersion: 1.15
    pools:
      - name: default-pool
        initialSize: 2
        config:
          diskType: pd-ssd
          diskSizeGb: 100
          machineType: n1-standard-1
      - name: workload
        initialSize: 1
        autoscaling:
          enabled: true
          minNodeCount: 1
          maxNodeCount: 8

serviceAccounts:
  - name: sa-gke-kyma-integration # present
    roles:
      - compute.admin
      - compute.networkAdmin
      - container.admin
      - container.clusterAdmin
      - dns.admin
      - iam.serviceAccountUser
      - storage.admin
      - cloudkms.cryptoKeyEncrypterDecrypter
  - name : sa-vm-kyma-integration # present
    roles :
      - compute.instanceAdmin
      - compute.osAdminLogin
      - iam.serviceAccountUser
  - name : sa-gcs-plank # present
    roles :
      - storage.objectAdmin
  - name : sa-gcr-push-kyma-project # present
    roles :
      - storage.objectCreator
  - name : sa-kyma-artifacts # present
    roles :
      -  storage.objectAdmin
  - name : sa-stability-fluentd-storage-writer
    roles:
      - storage.objectAdmin
  - name : sa-kyma-backup-restore
    roles :
      - storage.admin
      - storage.objectAdmin
      - compute.storageAdmin
  - name : sa-kyma-release-candidate
generics:
  - prefix: kyma-bot-npm-token
    key: token
  - prefix: kyma-bot-github-token
    key: token
  - prefix: kyma-bot-github-ssh
    key: key.pem
  - prefix: sap-slack-bot-token
    key: token
  - prefix: slack-nightly-token
    key: token
  - prefix: nightly-github-integration-app-client-id
    key: client-id
  - prefix: nightly-github-integration-app-client-secret
    key: client-secret
  - prefix: weekly-github-integration-app-client-id
    key: client-id
  - prefix: weekly-github-integration-app-client-secret
    key: client-secret
  - prefix: kyma-alerts-slack-api-url
    key: secret
  - prefix: kyma-snyk-token
    key: secret
  - prefix: kyma-azure-credential-id
    key: subscription-id
  - prefix: kyma-azure-credential-app-id
    key: subscription-app-id
  - prefix: kyma-azure-credential-secret
    key: subscription-secret
  - prefix: kyma-azure-credential-tenant
    key: subscription-tenant
  - prefix: nightly-aks-github-integration-app-client-id
    key: client-id
  - prefix: nightly-aks-github-integration-app-client-secret
    key: client-secret
  - prefix: service-catalog-crd-periodic-github-integration-app-client-id
    key: client-id
  - prefix: service-catalog-crd-periodic-github-integration-app-client-secret
    key: client-secret


