functionEnabled: true
# Forwarded event type
eventType: "prowjob.failed.v1"
#
subscriptionAppName: "pubsub-connector"
#
subscriptionServiceName: "prowjob-failed-v1"
#
subscriptionNamespace: "slack-connector"
# Slack channel name to send messages.
notificationSlackChannel: "kyma-ci-force"
# Path to directory with function code. Relative to repository root.
functionBaseDir: "/development/kyma-slack-connector/notifyCommiterFunction"
# Branch name with function code.
branch: "main"
