image:
  repository: eu.gcr.io/kyma-project/pr/test-log-collector  # will be updated after this PR is merged
  tag: PR-2668
  pullPolicy: IfNotPresent

serviceAccountName: ""

slackToken: ""

nameOverride: ""
fullnameOverride: ""