default-commit-tag:
  name: "default_tag"
  value: "v{{ .Date }}-{{ .ShortSHA }}"
  validation: "^(v[0-9]{8}-[0-9a-f]{8})$"
default-pr-tag:
  name: "default_tag"
  value: "PR-{{ .PRNumber }}"
  validation: "^(PR-[0-9]+)$"
registry:
  - europe-docker.pkg.dev/kyma-project/prod
dev-registry:
  - europe-docker.pkg.dev/kyma-project/dev
reproducible: false
log-format: json
ado-config:
  ado-organization-url: https://dev.azure.com/hyperspace-pipelines
  ado-project-name: kyma
  ado-pipeline-id: 14902
  ado-retry-strategy:
    attempts: 3
    delay: 5s
  ado-refresh-interval: 30s
cache:
  enabled: true
  cache-repo: europe-docker.pkg.dev/kyma-project/cache/cache
  cache-run-layers: true
sign-config:
  enabled-signers:
    "*":
      - signify-prod
  signers:
    - name: signify-prod
      type: notary
      job-type:
        - postsubmit
        - workflow_dispatch
      config:
        endpoint: https://signing.repositories.cloud.sap/signingsvc/sign
        timeout: 5m
        retry-timeout: 10s
        secret:
          path: /secret-prod/secret.yaml
          type: signify