tag-template: 'v{{ .Date }}-{{ .ShortSHA }}'
registry:
  - eu.gcr.io/kyma-project
  - europe-docker.pkg.dev/kyma-project/prod
dev-registry:
  - eu.gcr.io/kyma-project
  - europe-docker.pkg.dev/kyma-project/dev
reproducible: false
log-format: json
cache:
  enabled: true
  cache-repo: europe-docker.pkg.dev/kyma-project/cache/cache
  cache-run-layers: true
sign-config:
  enabled-signers:
    '*':
      - signify-dev
      - signify-prod
  signers:
    - name: signify-dev
      type: notary
      job-type:
        - presubmit
        - postsubmit
      config:
        endpoint: https://signing-dev.repositories.cloud.sap/signingsvc/sign
        timeout: 5m
        retry-timeout: 10s
        secret:
          path: /secret/secret.yaml
          type: signify
    - name: signify-prod
      type: notary
      job-type:
        - postsubmit
      config:
        endpoint: https://signing.repositories.cloud.sap/signingsvc/sign
        timeout: 5m
        retry-timeout: 10s
        secret:
          path: /secret-prod/secret.yaml
          type: signify