presubmits: # runs on PRs
  kyma-project/control-plane:
    - name: pre-control-plane-components-kyma-environment-broker
      annotations:
        owner: "gopher"
        description: "Main KEB unit testing pipeline"
        pipeline.trigger: "pr-submit"
      labels:
        prow.k8s.io/pubsub.project: "sap-kyma-prow"
        prow.k8s.io/pubsub.runID: "pre-control-plane-components-kyma-environment-broker"
        prow.k8s.io/pubsub.topic: "prowjobs"
        preset-dind-enabled: "true"
        preset-docker-push-repository-control-plane: "true"
        preset-kyma-kms-sign-key: "true"
        preset-sa-gcr-push: "true"
      run_if_changed: "^components/kyma-environment-broker/|^scripts/"
      skip_report: false
      decorate: true
      path_alias: github.com/kyma-project/control-plane
      cluster: untrusted-workload
      max_concurrency: 10
      branches:
        - ^master$
        - ^main$
      extra_refs:
        - org: kyma-project
          repo: test-infra
          path_alias: github.com/kyma-project/test-infra
          base_ref: main
      spec:
        containers:
          - image: "eu.gcr.io/kyma-project/test-infra/buildpack-golang:v20230323-a1ac96db"
            securityContext:
              privileged: true
            command:
              - "/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/build-generic.sh"
            args:
              - "/home/prow/go/src/github.com/kyma-project/control-plane/components/kyma-environment-broker"
            resources:
              requests:
                memory: 3Gi
                cpu: 2
        tolerations:
          - key: dedicated
            operator: Equal
            value: high-cpu
            effect: NoSchedule
        nodeSelector:
          dedicated: "high-cpu"
