prowjob_namespace: default
pod_namespace: test-pods
decorate_all_jobs: true

deck:
  spyglass:
    size_limit: 500000000 # 500MB
    gcs_browser_prefix: https://gcsweb.prow.build.kyma-project.io/gcs/
    testgrid_config: gs://k8s-testgrid/config
    testgrid_root: https://testgrid.k8s.io/
    tide_update_period: 1s
    lenses:
      - lens:
          name: metadata
        required_files:
          - started.json|finished.json
      - lens:
          config:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: junit
        required_files:
          - .*/junit.*\.xml
      - lens:
          name: html
        required_files:
          - ^artifacts/report.*\.html$
      - lens:
          name: podinfo
        required_files:
          - podinfo.json
  branding:
    header_color: "#ff0000"
    logo: "/static/extensions/logo.svg"
    favicon: "/static/extensions/favicon.png"

plank:
  job_url_prefix_config:
    "*": https://status-dev.prow.build.kyma-project.io/view/
  report_templates:
    '*': >-
      [Full PR test history](https://status-dev.prow.build.kyma-project.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
      [Your PR dashboard](https://status-dev.prow.build.kyma-project.io/pr?query=is:pr+state:open+author:{{with
      index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  max_concurrency: 100 # Limit of concurrent ProwJobs. Need to be adjusted depending of the cluster size.
  pod_pending_timeout: 60m
  default_decoration_configs:
    "*":
      timeout: 3h
      grace_period: 10m
      gcs_configuration:
        bucket: upgrade-prow-logs
        path_strategy: explicit
      gcs_credentials_secret: sa-gcs-plank
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20210407-51f95c2d52
        entrypoint: gcr.io/k8s-prow/entrypoint:v20210407-51f95c2d52
        initupload: gcr.io/k8s-prow/initupload:v20210407-51f95c2d52
        sidecar: gcr.io/k8s-prow/sidecar:v20210407-51f95c2d52

sinker:
  max_prowjob_age: 48h
  max_pod_age: 5h
  resync_period: 1m
  terminated_pod_ttl: 30m

tide:
  merge_method:
    kyma-test-infra-dev/test-infra: squash
  target_url: https://status-dev.prow.build.kyma-project.io/tide
  queries:
    - labels:
        - lgtm
      missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
        - do-not-merge/invalid-commit-message
      orgs:
        - kyma-test-infra-dev
      reviewApprovedRequired: true
  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true

push_gateway:
  endpoint: pushgateway
  serve_metrics: true

slack_reporter_configs:
  '*':
    job_types_to_report:
      - postsubmit
      - periodic
      - batch
    job_states_to_report:
      - failure
      - error
    channel: kyma-ci-force
    report_template: |
      *Name:* {{.Spec.Job}}
      *Type:* {{.Spec.Type}}
      *Status:* {{.Status.State}}
      {{with .Spec.Refs}}*Repository:* {{.Org}}/{{.Repo}}
      *Commit:* <{{.BaseLink}}|{{printf "%.7s" .BaseSHA}}>
      {{end}}*<{{.Status.URL}}|View logs>*

branch-protection:
  protect: true
  enforce_admins: true
  required_pull_request_reviews:
    require_code_owner_reviews: true
    required_approving_review_count: 1
    dismiss_stale_reviews: true
  orgs:
    kyma-test-infra-dev:
      protect: true
      required_status_checks:
        contexts:
          - "tide"
