required = ["k8s.io/test-infra/prow/cmd/checkconfig"]

# vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:246:13: cannot use expiresIn (type string) as type json.Number in field value
# vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:247:13: cannot use expiresOn (type string) as type json.Number in field value
# vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:248:13: cannot use expiresOn (type string) as type json.Number in field value
# vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:265:23: cannot use token.token.ExpiresIn (type json.Number) as type string in assignment
# vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:266:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "bca49d5b51a50dc5bb17bbf6204c711c6dbded06"

# vendor/k8s.io/test-infra/prow/client/clientset/versioned/scheme/register.go:55:2: undefined: "github.com/kyma-project/test-infra/development/checker/vendor/k8s.io/apimachinery/pkg/util/runtime".Must
[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

# vendor/k8s.io/client-go/plugin/pkg/client/accessmanager/azure/azure.go:300:8: cannot use spt.Token (type func() adal.Token) as type adal.Token in field value
[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"

[[constraint]]
  name = "k8s.io/test-infra"
  revision = "e5e370fd14bacee1c15cdc50652ec0d3fb433700"

[prune]
  go-tests = true
  unused-packages = true