name: autobump-docs-index-md.yml

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  workflow_dispatch: {}

env:
  AUTOBUMP_CONFIG_PATH: configs/autobump-config/test-infra-markdown-index-autobump-config.yaml

jobs:
  autobump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: post-test-infra-markdown-index-autobump
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup git config
        run: |
          GIT_USERNAME=$(grep "gitName" ${{ env.AUTOBUMP_CONFIG_PATH }} | cut -d '"' -f 2)
          GIT_EMAIL=$(grep "gitEmail" ${{ env.AUTOBUMP_CONFIG_PATH }} | cut -d '"' -f 2)
          git config user.name "$GIT_USERNAME"
          git config user.email "$GIT_EMAIL"

          git config --unset-all http.https://github.com/.extraheader

      - name: Authenticate in GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GH_COM_KYMA_PROJECT_GCP_WORKLOAD_IDENTITY_FEDERATION_PROVIDER }}

      - name: Get kyma bot token from Secret Manager
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            kyma-autobump-token:${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}/${{ vars.KYMA_AUTOBUMP_BOT_GITHUB_SECRET_NAME }}

      - name: Store Github Token for autobumper
        run: |
          echo "${{ steps.secrets.outputs.kyma-autobump-token }}" > ~/token

      - name: Run markdown index autobump
        run: |
          docker run --rm \
            -v ~/token:/etc/github/token:ro \
            -v ${{ github.workspace }}:/github/test-infra \
            --workdir /github/test-infra \
            --privileged \
            --cap-drop ALL \
            europe-docker.pkg.dev/kyma-project/prod/markdown-index:v20241209-6cfc7131 \
            --config=${{ env.AUTOBUMP_CONFIG_PATH }} \
            --labels-override=kind/chore,area/documentation
