name: image-autobumper
on:
  workflow_call:
    inputs:
      docker-image:
        description: 'Docker image with tag to be used'
        default: 'europe-docker.pkg.dev/kyma-project/prod/image-autobumper:v20250722-1e1b3698'
        type: string
      autobump-config-path:
        description: 'Path to the autobump config file, relative to the repository root'
        default: 'configs/autobump-config/test-infra-autobump-config.yaml'
        type: string

jobs:
  autobump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GH_COM_KYMA_PROJECT_GCP_WORKLOAD_IDENTITY_FEDERATION_PROVIDER }}

      - name: Get kyma bot token from Secret Manager
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            kyma-autobump-token:${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}/${{ vars.KYMA_AUTOBUMP_BOT_GITHUB_SECRET_NAME }}

      - name: Store Github Token for autobumper
        run: |
          echo ${{ steps.secrets.outputs.kyma-autobump-token }} > ~/token
          chmod 644 ~/token
          
      - name: Checkout repository
        uses: actions/checkout@v4

        # Setup git config with commiter data from config
        # Prevent silent passing github token
        # see https://stackoverflow.com/a/69979203/23148781
      - name: Setup git config
        run: |
          GIT_USERNAME=$(grep "gitName" ${{ inputs.autobump-config-path }} | cut -d '"' -f 2)
          GIT_EMAIL=$(grep "gitEmail" ${{ inputs.autobump-config-path }} | cut -d '"' -f 2)
          git config user.name $GIT_USERNAME
          git config user.email $GIT_EMAIL

          git config --unset-all http.https://github.com/.extraheader

      - name: Run Docker container
        run: |
          docker run \
            --rm \
            --cap-drop=ALL \
            --privileged \
            -v ${{ github.workspace }}:/workspace \
            -v ~/token:/etc/github/token:ro \
            -w /workspace \
            ${{ inputs.docker-image }} \
            --autobump-config=${{ inputs.autobump-config-path }}
