name: pull-image-builder-test

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/pull-image-builder-test.yml"
      - ".github/workflows/image-builder.yml"
      - ".github/actions/expose-jwt-action/**"
      - ".github/actions/image-builder/**"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: echo "TAG=v0.0.1-test" >> "$GITHUB_OUTPUT"
      - name: Echo the tag
        run: echo ${{ steps.get_tag.outputs.TAG }}
  build-image:
    needs: compute-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test-infra repository
        uses: actions/checkout@v4
        with:
          repository: kyma-project/test-infra
          ref: ${{ github.event.pull_request_target.head.ref }}
      - name: Build image
        uses: ./.github/workflows/image-builder.yml
        with:
          name: test-infra/ginkgo
          dockerfile: prow/images/ginkgo/Dockerfile
          context: .
          env-file: "envs"
          tags: ${{ needs.compute-tag.outputs.tag }}
  test-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Test image
        run: echo "Testing images ${{ needs.build-image.outputs.images }}"

