name: pull-unit-test-go

on:
  # This workflow is triggered by workflow controller.
  workflow_call:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: kyma-project/test-infra/.github/actions/checkout@main
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: '1.25.2'
      # https://github.com/golang/go/issues/75031
      - name: Set toolchain version
        run: go env -w GOTOOLCHAIN=go1.25.1+auto
      - run: go test -cover ./...
