name: workflow-controller-build-1

on:
  pull_request_target: 
    types: [opened, synchronize, reopened, ready_for_review]
  push:
   branches-ignore:
     - gh-readonly-*/**
     - dependabot/**
  merge_group: 

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.pathFilters.outputs.changes }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: kyma-project/test-infra
          ref: main
      - uses: dorny/paths-filter@v3
        id: pathFilters
        with:
          filters: .github/controller-filters.yaml

  build-cors-proxy:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-cors-proxy-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-cors-proxy.yml@main

  build-dashboard-token-proxy:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-dashboard-token-proxy-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-dashboard-token-proxy.yml@main

  build-github-webhook-gateway:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-github-webhook-gateway-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-github-webhook-gateway.yml@main

  build-image-builder:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-image-builder-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-image-builder.yml@main

  build-image-detector:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-image-detector-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-image-detector.yml@main

  build-image-syncer:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-image-syncer-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-image-syncer.yml@main

  build-image-url-helper:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-image-url-helper-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-image-url-helper.yml@main

  build-markdown-index:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-markdown-index-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-markdown-index.yml@main
  
